INSERT INTO cards (card_name, tag, suit, health, damage, image_front, image_back)
VALUES
('Ace of Spades', 'A', 'Spades', 0, 1, '["https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_spade/tile000.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_spade/tile001.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_spade/tile002.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_spade/tile003.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_spade/tile004.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_spade/tile005.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_spade/tile006.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_spade/tile007.png"]', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Ace of Hearts', 'A', 'Hearts', 0, 1, '["https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_hearts/tile000.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_hearts/tile001.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_hearts/tile002.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_hearts/tile003.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_hearts/tile004.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_hearts/tile005.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_hearts/tile006.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_hearts/tile007.png"]', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Ace of Diamonds', 'A', 'Diamonds', 0, 1, '["https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_diamond/tile000.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_diamond/tile001.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_diamond/tile002.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_diamond/tile003.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_diamond/tile004.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_diamond/tile005.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_diamond/tile006.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_diamond/tile007.png"]', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Ace of Clubs', 'A', 'Clubs', 0, 1, '["https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_club/tile000.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_club/tile001.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_club/tile002.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_club/tile003.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_club/tile004.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_club/tile005.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_club/tile006.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/ace/ace_club/tile007.png"]', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),


('Deuce of Spades', '2', 'Spades', 0, 2, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/deuce_of_spades.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Deuce of Hearts', '2', 'Hearts', 0, 2, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/deuce_of_hearts.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Deuce of Diamonds', '2', 'Diamonds', 0, 2, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/deuce_of_diamonds.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Deuce of Clubs', '2', 'Clubs', 0, 2, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/deuce_of_clubs.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),


('Three of Spades', '3', 'Spades', 0, 3, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/three_of_spades.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Three of Hearts', '3', 'Hearts', 0, 3, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/three_of_hearts.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Three of Diamonds', '3', 'Diamonds', 0, 3, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/three_of_diamond.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Three of Clubs', '3', 'Clubs', 0, 3, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/three_of_clubs.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),


('Four of Spades', '4', 'Spades', 0, 4, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/four_of_spades.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Four of Hearts', '4', 'Hearts', 0, 4, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/four_of_hearts.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Four of Diamonds', '4', 'Diamonds', 0, 4, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/four_of_diamonds.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Four of Clubs', '4', 'Clubs', 0, 4, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/four_of_clubs.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),


('Five of Spades', '5', 'Spades', 0, 5, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/five_of_spades.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Five of Hearts', '5', 'Hearts', 0, 5, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/five_of_hearts.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Five of Diamonds', '5', 'Diamonds', 0, 5, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/five_of_diamonds.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Five of Clubs', '5', 'Clubs', 0, 5, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/five_of_clubs.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),


('Six of Spades', '6', 'Spades', 0, 6, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/six_of_spades.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Six of Hearts', '6', 'Hearts', 0, 6, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/six_of_hearts.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Six of Diamonds', '6', 'Diamonds', 0, 6, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/six_of_diamonds.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Six of Clubs', '6', 'Clubs', 0, 6, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/six_of_clubs.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),


('Seven of Spades', '7', 'Spades', 0, 7, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/seven_of_spades.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Seven of Hearts', '7', 'Hearts', 0, 7, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/seven_of_hearts.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Seven of Diamonds', '7', 'Diamonds', 0, 7, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/seven_of_diamond.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Seven of Clubs', '7', 'Clubs', 0, 7, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/seven_of_clubs.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),



('Eight of Spades', '8', 'Spades', 0, 8, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/eight_of_spades.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Eight of Hearts', '8', 'Hearts', 0, 8, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/eight_of_hearts.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Eight of Diamonds', '8', 'Diamonds', 0, 8, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/eight_of_diamonds.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Eight of Clubs', '8', 'Clubs', 0, 8, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/eight_of_clubs.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),



('Nine of Spades', '9', 'Spades', 0, 9, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/nine_of_spades.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Nine of Hearts', '9', 'Hearts', 0, 9, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/nine_of_hearts.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Nine of Diamonds', '9', 'Diamonds', 0, 9, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/nine_of_diamonds.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Nine of Clubs', '9', 'Clubs', 0, 9, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/nine_of_clubs.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),



('Ten of Spades', '10', 'Spades', 0, 10, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/ten_of_spades.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Ten of Hearts', '10', 'Hearts', 0, 10, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/ten_of_hearts.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Ten of Diamonds', '10', 'Diamonds', 0, 10, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/ten_of_diamonds.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Ten of Clubs', '10', 'Clubs', 0, 10, 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/ten_of_clubs.png', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),


('Jack of Spades', 'J', 'Spades', 20, 10, '["https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_spade/tile000.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_spade/tile001.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_spade/tile002.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_spade/tile003.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_spade/tile004.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_spade/tile005.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_spade/tile006.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_spade/tile007.png"]', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Jack of Hearts', 'J', 'Hearts', 20, 10, '["https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_hearts/tile000.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_hearts/tile001.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_hearts/tile002.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_hearts/tile003.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_hearts/tile004.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_hearts/tile005.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_hearts/tile006.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_hearts/tile007.png"]', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Jack of Diamonds', 'J', 'Diamonds', 20, 10, '["https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_diamond/tile000.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_diamond/tile001.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_diamond/tile002.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_diamond/tile003.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_diamond/tile004.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_diamond/tile005.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_diamond/tile006.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_diamond/tile007.png"]', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Jack of Clubs', 'J', 'Clubs', 20, 10, '["https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_club/tile000.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_club/tile001.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_club/tile002.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_club/tile003.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_club/tile004.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_club/tile005.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_club/tile006.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/jack/jack_club/tile007.png"]', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Queen of Spades', 'Q', 'Spades', 30, 15, '["https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_spade/tile000.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_spade/tile001.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_spade/tile002.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_spade/tile003.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_spade/tile004.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_spade/tile005.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_spade/tile006.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_spade/tile007.png"]', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Queen of Hearts', 'Q', 'Hearts', 30, 15, '["https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_hearts/tile000.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_hearts/tile001.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_hearts/tile002.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_hearts/tile003.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_hearts/tile004.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_hearts/tile005.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_hearts/tile006.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_hearts/tile007.png"]', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Queen of Diamonds', 'Q', 'Diamonds', 30, 15, '["https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_diamond/tile000.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_diamond/tile001.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_diamond/tile002.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_diamond/tile003.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_diamond/tile004.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_diamond/tile005.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_diamond/tile006.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_diamond/tile007.png"]', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Queen of Clubs', 'Q', 'Clubs', 30, 15, '["https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_club/tile000.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_club/tile001.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_club/tile002.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_club/tile003.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_club/tile004.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_club/tile005.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_club/tile006.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/queen/queen_club/tile007.png"]', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('King of Spades', 'K', 'Spades', 40, 20, '["https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_spade/tile000.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_spade/tile001.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_spade/tile002.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_spade/tile003.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_spade/tile004.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_spade/tile005.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_spade/tile006.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_spade/tile007.png"]', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('King of Hearts', 'K', 'Hearts', 40, 20, '["https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_hearts/tile000.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_hearts/tile001.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_hearts/tile002.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_hearts/tile003.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_hearts/tile004.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_hearts/tile005.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_hearts/tile006.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_hearts/tile007.png"]', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('King of Diamonds', 'K', 'Diamonds', 40, 20, '["https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_diamond/tile000.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_diamond/tile001.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_diamond/tile002.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_diamond/tile003.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_diamond/tile004.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_diamond/tile005.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_diamond/tile006.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_diamond/tile007.png"]', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('King of Clubs', 'K', 'Clubs', 40, 20, '["https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_club/tile000.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_club/tile001.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_club/tile002.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_club/tile003.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_club/tile004.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_club/tile005.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_club/tile006.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/king/king_club/tile007.png"]', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Jester Red', 'Jester', 'Jester', 0, 0, '["https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/joker/joker_lies/tile000.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/joker/joker_lies/tile001.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/joker/joker_lies/tile002.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/joker/joker_lies/tile003.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/joker/joker_lies/tile004.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/joker/joker_lies/tile005.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/joker/joker_lies/tile006.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/joker/joker_lies/tile007.png"]', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png'),
('Jester Black', 'Jester', 'Jester', 0, 0, '["https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/joker/joker_truth/tile000.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/joker/joker_truth/tile001.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/joker/joker_truth/tile002.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/joker/joker_truth/tile003.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/joker/joker_truth/tile004.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/joker/joker_truth/tile005.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/joker/joker_truth/tile006.png","https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/sprites/joker/joker_truth/tile007.png"]', 'https://raw.githubusercontent.com/tothenextcode/pixelcide/main/frontend/src/assets/cards/card_back.png');
