INSERT INTO games (status, number_of_moves, finished_at, started_at)
VALUES
('WIN',   72, NOW() - INTERVAL '1 DAY',    NOW() - INTERVAL '1 DAY'    - INTERVAL '35 MINUTES'),
('LOSS',  63, NOW() - INTERVAL '3 DAYS',   NOW() - INTERVAL '3 DAYS'   - INTERVAL '30 MINUTES'),
('LOSS',  21, NOW() - INTERVAL '4 DAYS',   NOW() - INTERVAL '4 DAYS'   - INTERVAL '10 MINUTES'),
('LOSS',  44, NOW() - INTERVAL '10 DAYS',  NOW() - INTERVAL '10 DAYS'  - INTERVAL '25 MINUTES'),
('WIN',   75, NOW() - INTERVAL '20 DAYS',  NOW() - INTERVAL '20 DAYS'  - INTERVAL '30 MINUTES'),
('LEAVE', 13, NOW() - INTERVAL '1 MONTH',  NOW() - INTERVAL '1 MONTH'  - INTERVAL '2 MINUTES');
