DROP TABLE IF EXISTS games CASCADE;

-- CREATE GAME
CREATE TABLE games (
  id SERIAL PRIMARY KEY,
  status VARCHAR(10) NOT NULL,
  number_of_moves SMALLINT DEFAULT 0,
  finished_at TIMESTAMP NOT NULL,
  started_at TIMESTAMP NOT NULL
);